# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/contract_builder"
    schedule:
      interval: "weekly"
    groups:
      npm_and_yarn:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    groups:
      npm_and_yarn:
        patterns:
          - "*"

